indexing:
  index_name: "Document"
  igni_model_path: none
  batch_size: 4
  similarity: cosine
  do_eval: false
  igni_filters_path: null


process:
  max_seq_len: 128
  batch_size: 4

log:
  log_epoch_metrics: true
  log_batch_metrics: true


clustering:

  embedder:
    name_or_path: intfloat/multilingual-e5-base
    pooling_mode: mean
    prefix: "query: "

  transformers_backend:
    batch_size: 10

  bertopic:
    top_n_words: 10
    n_gram_range: [1, 1]
    min_topic_size: 5
    calculate_probabilities: false

  umap:
    n_components: 2
    n_neighbors: 3
    min_dist: 0.1
    metric: cosine